name: HelloWorld
version: 1.0
author: QureMC
main: xyz.qurequre.firstplugin.Main
description: Our first minecraft plugin!

commands:
  cur:
    aliases: [cu]
    description: Sending your current Gamemode!
